// packages/backend/src/routes/market.routes.ts
import { Router, Request, Response } from 'express';
import { MarketplaceService } from '../services/marketplace.service.js';
import { AgentManager } from '../agent-manager.js';

export function createMarketRoutes(marketplace: MarketplaceService): Router {
  const router = Router();

  //  1. SKILL.MD ROUTE
  router.get('/agents/:id/skill.md', (req: Request, res: Response) => {
    const { id } = req.params;
    
    // Try find by ID first
    let agent = marketplace.getAgent(id);
    
    // If not found, try search in all agents
    if (!agent) {
      const agentsList = marketplace.listAgents();
      agent = agentsList.find((a: any) => a.id === id || a.wallet === id) as any;
    }
    
    if (!agent) {
      res.set('Content-Type', 'text/plain');
      return res.status(404).send('Agent not found');
    }

    // Generate skill.md content
    const toolsMd = (agent.tools || []).map((tool: any) => 
`### ${tool.name}

**Description:** ${tool.description}

**Price:** ${tool.price} ${tool.currency || 'XLM'}

**Input Schema:**
\`\`\`json
${JSON.stringify(tool.inputSchema || { type: 'object', properties: {} }, null, 2)}
\`\`\`
`
    ).join('\n') || 'No tools available.';

    const skillMd = `# ${agent.name || 'Unknown Agent'}

${agent.description || 'No description available.'}

## Category
${agent.category || 'general'}

## Wallet
${agent.wallet || agent.id}

## Status
${agent.healthStatus || 'unknown'}

## Available Tools

${toolsMd}

## How to Use This Agent

1. AI model reads this skill.md manifest
2. Parses available tools and input schemas
3. Calls tool endpoint via HTTP POST/GET
4. Receives HTTP 402 Payment Required response
5. Creates payment transaction on Stellar/Soroban
6. Retries request with payment proof headers
7. Receives actual tool result

## Payment Flow

- Network: Stellar Testnet
- Asset: XLM or USDC
- Payment Method: x402 protocol
- Escrow: Soroban smart contract

---
*Generated by MagentiX Marketplace*
`;

    res.set('Content-Type', 'text/markdown; charset=utf-8');
    res.send(skillMd);
  });

  // 2. GET ALL AGENTS
  router.get('/agents', (req: Request, res: Response) => {
    const { category } = req.query;
    const agents = marketplace.listAgents(category as string);
    res.json({ agents });
  });

  // GET AGENT BY ID (lebih general - harus di bawah skill.md)
  router.get('/agents/:id', (req: Request, res: Response) => {
    const { id } = req.params;
    
    // Try find by ID first
    const agent = marketplace.getAgent(id);
    if (agent) {
      return res.json(agent);
    }
    
    // Try find by wallet
    const agentsList = marketplace.listAgents();
    const foundAgent = agentsList.find((a: any) => a.wallet === id);
    
    if (foundAgent) {
      return res.json(foundAgent);
    }
    
    return res.status(404).json({ error: 'Agent not found' });
  });

  // 4. NEW: TOOL CALL ENDPOINT with x402 payment flow
  router.post('/agents/:agentId/tools/:toolName/call', async (req: Request, res: Response) => {
    const { agentId, toolName } = req.params;
    const { input, callerWallet, x402_reference } = req.body;
    const paymentSignature = req.headers['payment-signature'] as string;

    console.log(`🔧 Tool call: ${agentId}#${toolName} from ${callerWallet?.substring(0,10)}...`);

    // 1. Find the agent
    const agent = marketplace.getAgent(agentId);
    if (!agent) {
      return res.status(404).json({ error: 'Agent not found' });
    }

    // 2. Find the tool
    const tool = agent.tools?.find((t: any) => t.name === toolName);
    if (!tool) {
      return res.status(404).json({ error: `Tool ${toolName} not found` });
    }

    // 3. Check if payment signature is provided
    if (!paymentSignature) {
      // No payment yet - return 402 with payment requirements
      console.log(`💳 Payment required for ${toolName}`);
      
      return res.status(402).json({
        error: 'Payment Required',
        x402: {
          description: `Payment required to call ${toolName}`,
          accepts: [{
            payTo: agent.wallet,  // Agent's wallet receives payment
            asset: 'XLM',
            amount: tool.price,   // Tool price in stroops
            memo: x402_reference || `tool:${toolName}:${Date.now()}`,
            network: 'testnet'
          }]
        }
      });
    }

    // 4. Verify payment signature
    console.log(`🔐 Verifying payment signature...`);
    
    try {
      const verified = await marketplace.verifyPaymentSignature(
        paymentSignature,
        callerWallet,
        agent.wallet,
        tool.price,
        x402_reference
      );

      if (!verified) {
        console.log(`❌ Payment verification failed`);
        return res.status(402).json({ error: 'Invalid payment signature' });
      }
      
      console.log(`✅ Payment verified!`);
      
      // Grant access after successful payment
      if (callerWallet) {
        marketplace.grantAccess(callerWallet, agentId);
      }

    } catch (e: any) {
      console.error(`❌ Payment verification error: ${e.message}`);
      return res.status(500).json({ error: 'Payment verification failed' });
    }

    // 5. Execute the tool (mock implementation)
    console.log(`🎯 Executing ${toolName}...`);
    
    let result: any;
    
    if (toolName === 'search_flights') {
      result = {
        flights: [
          { 
            id: 'GA001', 
            airline: 'Garuda Indonesia', 
            price: '1.5M IDR', 
            route: 'CGK-DPS', 
            date: '2026-05-01',
            departure: '08:00',
            arrival: '10:30'
          },
          { 
            id: 'GA002', 
            airline: 'Lion Air', 
            price: '1.2M IDR', 
            route: 'CGK-DPS', 
            date: '2026-05-01',
            departure: '14:00',
            arrival: '16:30'
          }
        ],
        query: input?.query || 'auto'
      };
    } 
    else if (toolName === 'analyze_market') {
      result = {
        symbol: input?.symbol || 'BTC/USD',
        price: '$65,432.10',
        change_24h: '+2.34%',
        signal: 'BUY',
        confidence: 0.85,
        indicators: {
          rsi: 58.2,
          macd: 'bullish',
          volume: 'high'
        }
      };
    }
    else if (toolName === 'execute_trade') {
      result = {
        order_id: `ORD_${Date.now()}`,
        status: 'filled',
        symbol: input?.symbol,
        side: input?.side,
        amount: input?.amount,
        executed_price: '$65,430.00',
        timestamp: new Date().toISOString()
      };
    }
    else if (toolName === 'get_flight_price') {
      result = {
        flight_id: input?.flight_id || 'GA001',
        base_price: '1.2M IDR',
        taxes: '150K IDR',
        total: '1.35M IDR',
        currency: 'IDR',
        valid_until: new Date(Date.now() + 300000).toISOString() // 5 min
      };
    }
    else if (toolName === 'book_flight') {
      result = {
        booking_id: `BK_${Date.now()}`,
        pnr: 'MAGX26',
        status: 'confirmed',
        e_ticket: `ET-${Math.random().toString(36).slice(2, 8).toUpperCase()}`,
        flight: input?.flight_id || 'GA001',
        passenger: input?.passenger || 'Agent User',
        timestamp: new Date().toISOString()
      };
    }
    else {
      // Generic fallback for unknown tools
      result = { 
        message: `Tool ${toolName} executed successfully`,
        input,
        timestamp: Date.now()
      };
    }

    console.log(`✅ Tool ${toolName} completed`);
    res.json({ success: true, data: result });
  });

  // 5. REGISTER AGENT
  router.post('/register', (req: Request, res: Response) => {
    try {
      const agentData = req.body;
      const agentId = marketplace.registerAgent(agentData);
      res.json({ success: true, agent_id: agentId });
    } catch (e: any) {
      res.status(500).json({ error: e.message });
    }
  });

  return router;
}